name: tictactoe
description: "A simple tic tac toe game."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flame: ^1.17.0
  go_router: ^7.0.0
  loading_animation_widget: ^1.2.1
  nes_ui: ^0.20.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
